framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    trusted_proxies: 'REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port']

    #esi: true
    #fragments: true

    http_client:
        default_options:
            verify_peer: true
            cafile: '%kernel.project_dir%/cacert.pem'

    error_controller: App\Controller\ErrorController::show

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
